version: '2.1'
services:
  dancestudio:
    container_name: 'dancestudio'
    networks:
      dancestudio:
        ipv4_address: 172.13.1.10
    build:
      context: '.'
      dockerfile: './cmd/server/Dockerfile'
    restart: on-failure
    ports:
      - '8080:8080'
    volumes:
      - '.:/app/server'
    depends_on:
      - 'mysql'
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: dancestudio
      MYSQL_USER: dancestudio
      MYSQL_PASSWORD: dancestudio
    networks:
      dancestudio:
        ipv4_address: 172.13.1.2
    container_name: 'mysql'
    ports:
      - '13306:3306'
networks:
    dancestudio:
        ipam:
            driver: default
            config:
                - subnet: 172.13.1.0/24

